### ISSUE TITLE
Google search not working in production version 

### ISSUE THREAD

**Issue by 5brian** [familyfriendlymikey/fuzzyhome#16]
When entering a query that is not a bookmark, it redirects to https://www.google.com/webhp

Does not happen on local build

**Comment by familyfriendlymikey** [comment]
Ah crap, what is the default bang set to? It must still have the `!` in it or something which is the deprecated syntax.

I didn't push a new version for so long since I was worried about something like this, but in the end it still makes more sense to push..

**Comment by familyfriendlymikey** [comment]
To be clear, the default bang should now be
```
https://www.google.com/search?q=$0
```

**Comment by 5brian** [comment]
Oh i forgot about that, i still had the old syntax, i changed the default bang and its working. My bad for the false issue

**Comment by familyfriendlymikey** [comment]
No, thank you, the issue is valid because other users will experience this problem but most of them probably aren't going to make an issue here. I'll fix it real quick.

**Comment by familyfriendlymikey** [comment]
0a2d5e1a40d0aa583eea404481ea22ebf0284a11 should fix it
