### ISSUE TITLE
Firefox Port

### ISSUE THREAD

**Issue by fhedman** [familyfriendlymikey/fuzzyhome#2]
Hey, any chance you could make a Firefox extension of fuzzyhome?

**Comment by familyfriendlymikey** [comment]
Not so much time these days to be honest, and I don't use Firefox anymore so it's hard to justify. It used to be browser agnostic/not tied to bookmarks, I believe this old version should be working fine: https://preview.fuzzyhome.pages.dev/

Then you can use some browser extension to change your new tab page to the url.

**Comment by fhedman** [comment]
Thanks! I'll give that a shot.
