### ISSUE TITLE
Allow launching of urls

### ISSUE THREAD

**Issue by shlomiuziel** [familyfriendlymikey/fuzzyhome#3]
Many times I want to start the browser, paste a url and directly go there.
With the default behavior, pasting a url and pressing enter will search the url in Google instead.
This requires jumping to the url address bar either using the mouse or with a shortcut, which is an extra step.

(By identifying urls and defaulting to launching them instead of searching in Google, daily workflows could greatly improve)

**Comment by familyfriendlymikey** [comment]
Implemented this. Will try to make a new release on the weekend.

**Comment by familyfriendlymikey** [comment]
will probably release this today
