### ISSUE TITLE
Allow multiple query parameters for bang bookmarks

### ISSUE THREAD

**Issue by shlomiuziel** [familyfriendlymikey/fuzzyhome#4]
The current bang implementation only supports one parameter, at the end of the url.
using formatted urls will allow multiple query parameters at varying locations.
for example : http://domain.com/{param1/{param2}

**Comment by familyfriendlymikey** [comment]
Implemented this, will try to release on weekend.

**Comment by familyfriendlymikey** [comment]
will probably release this today
