### ISSUE TITLE
Implement less accurate fuzzy finding

### ISSUE THREAD

**Issue by shlomiuziel** [familyfriendlymikey/fuzzyhome#5]
The current implementation seems to support cases like missing characters, but is not resilient to mistakes.
For example, for "Calendar" I'd expect to be able to search "calandar".

**Comment by familyfriendlymikey** [comment]
I'm happy to merge a PR for a setting that toggles this on/off using a preferably tiny zero-dependency Levenshtein distance package, but since I don't need it I'm closing for now.
