### ISSUE TITLE
Implement abbreviated fuzzy search

### ISSUE THREAD

**Issue by shlomiuziel** [familyfriendlymikey/fuzzyhome#6]
By implementing abbreviation based fuzzy search (e.g. gh for GitHub), 
there could be much better support out of the box without having to concatenate parenthesis at the end of the title.

**Comment by familyfriendlymikey** [comment]
Thanks for the suggestions! I really like this one.

I've toyed around with some of the other ones before but I'm open to trying again.

I don't know when I'll have time but I do intend to get around to it.

**Comment by familyfriendlymikey** [comment]
Actually I realized a while ago that this is already what the fuzzy searching does, it's just based on spaces rather than capital letters. So `git hub` would have the desired effect here, but it would be interesting to have the fuzzy search also respect letter case.

**Comment by familyfriendlymikey** [comment]
Looking back, I believe this is what the algorithm already does.
