### ISSUE TITLE
chrome protocol bookmarks don't work

### ISSUE THREAD

**Issue by jlabedzki** [familyfriendlymikey/fuzzyhome#9]
Bookmarking `chrome://extensions` doesn't work. Not sure if this is a limitation of chrome or the app itself. Was gunna poke around and try to make a PR but not familiar with imba.

Awesome extension btw.

**Comment by familyfriendlymikey** [comment]
Yeah I think that's a Chrome thing, I wanted this too but I don't think there is a way to implement it. Even in raw html if you click a simple link like this it will throw:
```
<a href='chrome://extensions'>go</a>
```
That said if somebody does find a workaround I'm happy to implement it.

And thank you :)
